# Generated by Django 4.2.6 on 2023-10-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converts/')),
                ('profile_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converted_file', to='profiles.profile')),
            ],
        ),
    ]
